ipdatabases:
  - name: lemarchedb
    plan: free
    databaseName: lemarche
    user: lemarche
p
services:
  - type: web
    plan: free
    name: lemarche
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn lemarche.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lemarchedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4