# Generated by Django 4.2.2 on 2024-07-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
    ]
