# Generated by Django 4.2.2 on 2024-07-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
